theme: jekyll-theme-simplex
# Site wide configuration

title: Academic Website of Data Acquisition Project
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: loddwwj
  avatar: bio-photo.jpg
  bio: "This is a sample Jekyll academic website."
  email: loddwwj@gmail.com
  # Do not include the @ symbol in your Twitter username
  github: loddwwj
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
